### ISSUE TITLE
sender中没有发送日志

### ISSUE THREAD

**Issue by wkshare** [open-falcon-archive/sender#1]
@UlricQin 
有个纠结的问题，sender没有发送告警。

已经配置模版：
![image](https://cloud.githubusercontent.com/assets/2918384/7827418/a33248d4-0459-11e5-812b-116117e8d1a8.png)

已经建立主机组，并套用模版：
![image](https://cloud.githubusercontent.com/assets/2918384/7827442/e68add58-0459-11e5-9c12-237645b51be0.png)

alarm dash中也已经出现对应的告警（告警是14小时前，也就是5月26号的）：
![image](https://cloud.githubusercontent.com/assets/2918384/7827451/0206d672-045a-11e5-85f2-ed0a88d39f7d.png)

再查看sender日志：（5月26号，并没有发送日志）

```
sender# ./control tail
all(#3): 4.6085<=10
Note:磁盘可用空间小于10%
Max:3, Current:3
Timestamp:2015-05-25 12:37:50
http://testserver:5050/template/view/1
>
2015/05/25 12:45:06 mail.go:51: <<<<==mail== 

2015/05/25 13:46:10 cfg.go:81: read config file: cfg.json successfully
2015/05/25 13:46:10 http.go:60: http listening 0.0.0.0:6066
```

这个sender该如何调整，求给个思路。

**Comment by jianhuihi** [comment]
我刚刚也遇到了

[root@ljh134 sender]# ./control tail
Endpoint:rabbit1.localdomain
Metric:net.port.listen
Tags:port=8888
all(#2): 0==0
Note:8.18SSDB挂了
Max:2, Current:1
Timestamp:2015-05-27 10:22:12
http://192.168.8.134:5050/template/view/2

> 2015/05/27 10:20:04 mail.go:51: <<<<==mail== 
> 
> 日志有信息，但是不发短信呢

**Comment by wkshare** [comment]
@jianhuihi 你贴的这个什么意思呢？

**Comment by jianhuihi** [comment]
配置sms 不发送短信呢

**Comment by UlricQin** [comment]
sender的逻辑比较简单，里边有个queue配置，只要与alarm配置的queue一致就没问题了

**Comment by UlricQin** [comment]
@jianhuihi 配置了sms不发短信你要检查你的接口是否符合规范，sender的调用方式是：

```
curl <你的短信http接口> -d "content=xxx&tos=18612181123"
```

**Comment by wkshare** [comment]
@UlricQin 
alarm的queue配置

```
cat alarm/cfg.json 
{
    "debug": true,
    "uicToken": "",
    "http": {
        "enabled": true,
        "listen": "0.0.0.0:7070"
    },
    "queue": {
        "sms": "/sms",
        "mail": "/mail"
    }
```

sender的queue配置

```
cat sender/cfg.json 
{
    "debug": true,
    "http": {
        "enabled": true,
        "listen": "0.0.0.0:6066"
    },
    "redis": {
        "addr": "127.0.0.1:6379",
        "maxIdle": 5
    },
    "queue": {
        "sms": "/sms",
        "mail": "/mail"
    },
```

**Comment by UlricQin** [comment]
@wkshare 看你了queue配置是没问题的，你重新触发一个报警试试，配置一个必然会触发的报警

**Comment by jianhuihi** [comment]
果然是接口问题，tks~

**Comment by wkshare** [comment]
@UlricQin 
新建一个load5_test的模版，并套用到机器
![image](https://cloud.githubusercontent.com/assets/2918384/7827596/d9dec64e-045b-11e5-8f9f-da52a1de6139.png)
![image](https://cloud.githubusercontent.com/assets/2918384/7827604/f0fe5e70-045b-11e5-84d2-ab8f81373856.png)
再次查看alarm dash，已经触发告警。
![image](https://cloud.githubusercontent.com/assets/2918384/7827623/29308138-045c-11e5-9741-6c75c104e11d.png)

再次查看sender日志：

```
tail sender/var/app.log 
all(#3): 4.6085<=10
Note:磁盘可用空间小于10%
Max:3, Current:3
Timestamp:2015-05-25 12:37:50
http://testserver:5050/template/view/1
>
2015/05/25 12:45:06 mail.go:51: <<<<==mail== 

2015/05/25 13:46:10 cfg.go:81: read config file: cfg.json successfully
2015/05/25 13:46:10 http.go:60: http listening 0.0.0.0:6066
```

**Comment by UlricQin** [comment]
redis的`/sms`和`/mail`这俩queue中有内容么

**Comment by UlricQin** [comment]
看看alarm的log有没有报错

**Comment by wkshare** [comment]
redis的内容：

```
keys *
(empty list or set)
```

alarm的日志有一些错误。
这些错误，是由于对alarm中三个api地址做了访问控制，导致的timeout：

```
    "api": {
        "portal": "http://testserver:5050",
        "uic": "http://testserver:8080",
        "links": "http://testserver:5090"
    }
```

修改访问控制后，sender中的日志正常。(问题已经解决，谢谢@UlricQin)

其他疑问：
alarm需要访问portal、uic、links这三个地址的作用分别是什么？

**Comment by UlricQin** [comment]
这个说起来就麻烦了，看看alarm代码吧

**Comment by wkshare** [comment]
thks
