### ISSUE TITLE
redis有密码认证如何处理

### ISSUE THREAD

**Issue by jeanphorn** [open-falcon-archive/sender#3]
我看目前redis配置方式为ip:port，但是redis有密码认证的时候呢？小白冒昧问一下

**Comment by jeanphorn** [comment]
在源码上做了改动，添加了密码验证部分。

**Comment by wangnan229** [comment]
> 
> 
> 我看目前redis配置方式为ip:port，但是redis有密码认证的时候呢？小白冒昧问一下

大神，能将如何修改源码以适应redis密码的方法教下我吗，非常感谢
